[package]
name = "paxmark"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = [ "derive" ] }
xattr = "1.3.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

