name: paxmark
on:
  pull_request:
    branches:
    - main
  merge_group:
    branches:
    - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    runs-on: ubuntu-latest
    name: paxmark build (${{ matrix.platform }})
    defaults:
      run:
        shell: bash
    steps:
    - uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        submodules: recursive
    - run: |
        rustup update --no-self-update stable
        rustup default stable
    - run: |
        rustup target add --toolchain stable "${{ matrix.platform }}"
    - run: cargo build --target "${{ matrix.platform }}" --bin paxmark
